# Generated by Django 4.0.1 on 2022-01-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderinfo_pizzas_pizza_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='user',
        ),
    ]
