# Generated by Django 4.0.1 on 2022-01-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pizzatype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
    ]
