# Generated by Django 4.0.1 on 2022-01-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_orderinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
    ]
